### ISSUE TITLE
Allow to pass custom headers & choose cache time

### ISSUE THREAD

**Issue by FJM-Slade** [krakend/krakend-jose#44]
Hello,

In my scenario one realm corresponds to one tenant. 
Since the jwk-url is static I can't have a dynamic URL for each tenant:
 (eg: something like "http://localhost/auth/realms/**${X-Tenant}**/protocol/openid-connect/certs").

One workaround that I tried was to allow passing the original Headers, where I could use the Tenant name to do a custom service where I could know what is the tenant where to check the keys.
But the jwk-url does not pass the original Headers...

I already mentioned this in the slack channel ([https://gophers.slack.com/archives/CANCJD0V8/p1604436717237800](https://gophers.slack.com/archives/CANCJD0V8/p1604436717237800)) and the solution was to build a new plugin...

So, would it be possible to allow, by configuration, to pass the original headers to the jwk url? And also mention if we do want to cache the result? 

Thanks,
Filipe

**Comment by alombarte** [comment]
Hi @FJM-Slade,

I am aware that this issue is old as fire in hell, but caching JWK URLs was always possible. You could back then create an endpoint with the cache module enabled (and even a martian modifier to override the Cache-Control header) and use as backend your JWK URL, or in more modern KrakenD use the caching attributes.

I didn't want to close the issue without providing an answer :)
